<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProductById($productId)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p.description, p.price')
            ->where('p.productId = :productId')
            ->setParameter('productId', $productId);

        $query = $qb->getQuery();
        $result = $query->getOneOrNullResult();

        return $result;
    }
}
